export const actionTypes = {
    FETCH_DATA_REQUEST: 'fetchDataRequest',
    FETCH_DATA_SUCCESS: 'fetchDataSuccess',
    FETCH_DATA_FAILURE: 'fetchDataFailure',
    SAVE_DATA_REQUEST: 'saveDataRequest',
    SAVE_DATA_SUCCESS: 'saveDataSuccess',
    SAVE_DATA_FAILURE: 'saveDataFailure',
    CHANGE_DATA: 'changeData',
    CHANGE_WINDOW_SIZES: 'changeWindowSizes',
    CHANGE_CURRENT_POSITION: 'changeCurrentPosition',
    CHANGE_MOUSE_POSITION: 'changeMousePosition',
    CHANGE_ZOOM: 'changeZoom',
    ADD_RIGHT_ROW: 'addRightRow',
    ADD_LEFT_ROW: 'addLeftRow',
    DISABLE_NEED_CLICKS: 'disableNeedClicks',
    SHOW_ERROR_WINDOW: 'showErrorWindow',
    CLOSE_ERROR_WINDOW: 'closeErrorWindow',
    CHANGE_SELECTED_CELLS: 'changeSelectedCells',
    CHANGE_GUIDE_LABEL: 'changeGuideLabel',
    CHANGE_CURRENT_YEAR: 'changeCurrentYear',
    CHANGE_CURRENT_SORT: 'changeCurrentSort',
    ADD_NEW_GUIDE: 'addNewGuide',
    REMOVE_GUIDE: 'removeGuide',
    CHANGE_AUTH_STATUS: 'changeAuthStatus',
    CHANGE_LOGIN: 'changeLogin',
    CHANGE_PASSWORD: 'changePassword'
};